apiVersion: apps/v1
kind: Deployment
metadata:
  name: g2g-model
  labels:
    app: g2g-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g2g-model
  template:
    metadata:
      labels:
        app: g2g-model
    spec:
      containers:
      - name: g2g-api
        image: g2g-model:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONPATH
          value: /app/src
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 20
