name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and type check
        run: |
          black --check src scripts tests || (echo "Run black" && exit 1)
          isort --check-only src scripts tests || (echo "Run isort" && exit 1)
          flake8 src scripts tests
          mypy src || true

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t g2g-model:ci .

